name: scripts
description: A simple command-line application.
version: 1.0.0+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  dart_appwrite: ^7.3.0

dev_dependencies:
  lints: ^2.0.1